### ISSUE TITLE
Track show progress

### ISSUE THREAD

**Issue by BitYog** [joshwcomeau/Tello#13]
If we could add what episodes we finished, then this tool would be awesome. 

For example, I’m on Mr. Robot Season 2 Episode 3 right now. If this shows up on my dashboard on the website, I can easily track all my shows. Could we have this feature?

**Comment by joshwcomeau** [comment]
Tracking episodes is the core feature of Tello :)

there's a bug right now where episodes aren't populated after adding the show; you gotta refresh. Hopefully will get a fix for that out shortly, kinda juggling too much atm though.

To mark an episode as seen, once the list is fetched, you just click on it. This is consistent across the 3 views

**Comment by BitYog** [comment]
My bad... I didn't notice this feature the first time I used Tello. I could use this afterwards, though. Closing this issue.
