### ISSUE TITLE
Shows with no airdate are treated as "aired"

### ISSUE THREAD

**Issue by joshwcomeau** [joshwcomeau/Tello#15]
Sometimes, TV Maze returns shows with no `airstamp`.

My selectors assume any date not in the future is aired, which means `null` gets turned into the Unix epoch, and it thinks the episodes are super old.

**Comment by joshwcomeau** [comment]
Fixed! Thanks for the heads-up, @clauderic

**Comment by clauderic** [comment]
🎉🎉🎉
