### ISSUE TITLE
Why are you turning it off?

### ISSUE THREAD

**Issue by frederikhors** [joshwcomeau/Tello#20]
Hi @joshwcomeau your work on Tello is amazing!

1. **Why are you turning it off?**

1. And how can we save the data?

**Comment by ktilcu** [comment]
Hey there! @joshwcomeau has graciously allowed me to take the domain and get the service running again. I have a few things to continue fixing but for now it's at least live again. tello.tv! For the short term I added a quick import feature under the settings tab to import those data files you may have exported.

**Comment by frederikhors** [comment]
Thanks!
